name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: get semantic release info
        run: echo new_release_version=${GITHUB_REF:11} >> $GITHUB_ENV
      - name: get package version
        id: package
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: check package version
        if: ${{ steps.package.outputs.prop != env.new_release_version }}
        run: |
          echo "invalid package version, expected: ${{env.new_release_version}}, got: ${{steps.package.outputs.prop}}"
          exit 1
      - run: bun install --no-save
      - run: bun run build
      - name: create .npmrc file
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> .npmrc
      - run: npm publish --access public
      - run: npm dist-tag add @e-krebs/react-library@${{env.new_release_version}} alpha
